sudo: false
addons:
  jwt:
    secure: GyukQwv3X/J/HMtGTxv1JFBiKHdYsdN1wdZXztwcvKnNIeQxSfXnZu3zWUUmuZtZAp9RGETWHmn/LmLoMBw7w6ZgJyHtn9SbEJbuLzkoVu/m860e2cX+/JTETTJUhVKpEisc8DIalEEv4V3qeQ0tn9tkZYxD3T4r0Fus+gF3ymQ+7QfIrEcbWqTHvb69CeREBbDYA3VA1WUf0yDG5lV17D7ogEClYPIYhK/Cmy/9NSSy7qFXu405o4wEMLkiG9wzeihUHMzJU324n7xJ6lwZI1Ku50kVS5Vf46LIX5pDEmM6uWDtZq9m6of6oAL166zW8V3DMnqmW6OMgjerQcmwR2njCx0PXKQhUDkepAb8Tj2XcPX11fSqyaZv8MnhGWRGrc97X6X0Erb4pAwa7wixgZPdDKDRer18X7+QrLAxnpq8AbECt/EJx6soRwmHSgD1apld/TvI6jkh2SpbbX3M4rpL6hKTQJoH4PiO+lzaOrLbQEtMvjriPTAY+7hfJyeg9Yxnhwcl0Aa7MuDXauHzR7is0payBrNDZqdbo7s+kxfBTj17ZNcz+Zo+EtI7eSitXAqMBqP0fr4J79Z/mrZ7D6GJ1tWff0lZiq6fPAlJGWaye9lQ7hikw1f9f47yN17Isf8/Z6BEZ33ZnxA2i1KOJwb6Pq6nLYFFo53Z9uuw208=
env:
  global:
  - SAUCE_USERNAME=NiklasMerz
  - TRAVIS_NODE_VERSION="4.2"
matrix:
  include:
  - env: PLATFORM=android-7.0
    os: linux
    language: android
    jdk: oraclejdk8
    android:
      components:
      - tools
before_install:
- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm
  && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm
  install $TRAVIS_NODE_VERSION
- node --version
- if [[ "$PLATFORM" =~ android ]]; then gradle --version; fi
- if [[ "$PLATFORM" =~ ios ]]; then npm install -g ios-deploy; fi
- if [[ "$PLATFORM" =~ android ]]; then echo y | android update sdk -u --filter android-25;
  fi
- git clone https://github.com/apache/cordova-paramedic /tmp/paramedic && pushd /tmp/paramedic
  && npm install && popd
- npm install -g cordova
install:
- npm install
script:
- node /tmp/paramedic/main.js --config pr/$PLATFORM --plugin $(pwd) --shouldUseSauce
  --buildName travis-plugin-device-$TRAVIS_JOB_NUMBER

